version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"